on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write  # 👈 This is required for PR comment posting

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY }}" >> $GITHUB_ENV
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json" >> $GITHUB_ENV

      - name: Run AuditAI Analysis
        run: |
          PYTHONPATH=. python scripts/run_analysis.py app/ > result.json

      - name: Post analysis result to PR
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: result.json
